galaxy_info:
  author: Guillaume Charbonnier
  description: Ensure system users are present

  license: MIT
  min_ansible_version: "2.2"

  platforms:
    - name: Ubuntu
      versions:
        - xenial
        - bionic
        - focal
        - jammy

dependencies: []
