galaxy_info:
  author: Guillaume Charbonnier
  description: Configure OpenSSH Server

  license: MIT
  min_ansible_version: "2.2"

  platforms:
    - name: Ubuntu
      versions:
        - xenial
        - bionic
        - focal
        - jammy

  galaxy_tags:
    - ssh
    - sshd
    - openssh-server

dependencies: []
